#!/usr/bin/env python

import argparse
import distutils.spawn
import os
import shutil
import stat
import subprocess
import multiprocessing
import json

project_root = os.path.dirname(os.path.abspath(__file__))
os.chdir(project_root)

needy = os.path.join(project_root, 'needy', 'scripts', 'needy')


def pkg_is_present(pkg):
    env = os.environ.copy()
    env['PKG_CONFIG_LIBDIR'] = ''
    return subprocess.call(['pkg-config', pkg, '--exists'], env=env) == 0

parser = argparse.ArgumentParser(description='Builds non-user-supplied dependencies.')
parser.add_argument('--needy-target-args', default='', help='arguments to select the needy target with')
parser.add_argument('--needy-satisfy-args', default='', help='the arguments to use with needy satisfy')
parser.add_argument('--configure', action='store_true', help='if true, configure will also be invoked')
parser.add_argument('--clean', action='store_true', help='clean prior to building')
parser.add_argument('-j', '--concurrency', default=multiprocessing.cpu_count(), type=int, help='build concurrency')
args = parser.parse_args()

dependencies = [
    'asio',
    'fmtlib',
    'gsl',
    'json11',
    'libsodium',
    'mnmlstc',
    'libcurl',
    'mbedtls',
]
owned_dependencies = [dep for dep in dependencies if not pkg_is_present(dep)]

needy_common_args = filter(None, args.needy_target_args.split())
needy_satisfy_args = filter(None, ['-j', str(args.concurrency)] + args.needy_satisfy_args.split())

if args.clean:
    subprocess.check_call([needy, 'clean'] + needy_common_args + owned_dependencies)

subprocess.check_call([needy, 'satisfy'] + needy_common_args + needy_satisfy_args + owned_dependencies)

pkgconfig_path = subprocess.check_output([needy, 'pkg-config-path'] + needy_common_args + owned_dependencies)

config_file = 'configure.json'
print('Writing configuration to {}'.format(config_file))
with open(config_file, 'w') as configure_json:
    configure_json.write(
        json.dumps({
            'env': {
                'PKG_CONFIG_PATH': '{}:{}'.format(pkgconfig_path, os.environ.get('PKG_CONFIG_PATH', '')),
            },
            'needy': {
                'common-args': needy_common_args,
                'satisfy-args': needy_satisfy_args,
            },
            'dependencies': dependencies,
            'owned-dependencies': owned_dependencies
        }, sort_keys=True, indent=4, separators=(',', ': ')))

if args.configure:
    subprocess.check_call('./configure')
else:
    print('Dependencies built. To use them, run ./configure')
