#!/bin/bash -e

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $script_dir/../..

export CXX=clang++-3.8
export CXXFLAGS=-stdlib=libc++

cat << PROJECT_CONFIG > project-config.jam
using clang : : $CXX :
    <cxxflags>$CXXFLAGS
    <linkflags>$CXXFLAGS
;
PROJECT_CONFIG

coverage_lib=$(find /usr/lib*/llvm-3.8/lib/ -name "libclang_rt.profile*.a")
cpu_count=$(nproc)

./build-deps --bootstrap-b2 --configure
./b2 tests/unit//run -j$cpu_count cxxflags="-coverage" linkflags="$coverage_lib"
