#!/bin/bash -e

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $script_dir/../..

./build-deps --bootstrap-b2 --configure

echo "using darwin ;" >> project-config.jam

cpu_count=$(sysctl -n hw.ncpu)

./b2 -j$cpu_count variant=release
./b2 -j$cpu_count variant=release tests/unit//run
./b2 -j$cpu_count variant=release tests/benchmarks//run
