#!/bin/bash -e

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $script_dir/../..

export CXX=clang++-3.8
export CXXFLAGS=-stdlib=libc++
export LDFLAGS=-lc++

if [[ -z $ANALYSIS ]] ; then
    # the benchmarks built with this would NOT be good with coverage
    ./scripts/build --install --enable-coverage
    ./tests/unit/dist/scraps-tests
else
    ./scripts/build --variant=debug --enable-analysis
fi
