#!/bin/bash -e

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $script_dir/../..

android_toolchain=$script_dir/../../toolchains/android/$NDK_VERSION/android-$API_LEVEL/arm-linux-androideabi-clang3.6

if [[ ! -d $android_toolchain ]] ; then
    echo "error: android toolchain not present in $android_toolchain"
    exit 1
fi

cat << PROJECT_CONFIG > project-config.jam
using clang-linux : android : $android_toolchain/bin/arm-linux-androideabi-clang++ :
    <linkflags>-march=armv7-a
    <linkflags>-latomic
;
PROJECT_CONFIG

cpu_count=$(nproc)

./build-deps --bootstrap-b2 --needy-target-args="-t android" --needy-satisfy-args="--android-toolchain=$android_toolchain" --configure
./b2 -j$cpu_count variant=release target-os=android scraps tests/unit
