#!/bin/bash -e

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
$script_dir/install-common-dependencies

type pkg-config 2>/dev/null || brew install pkg-config
type python     2>/dev/null || brew install python
type python3    2>/dev/null || brew install python3
type cmake      2>/dev/null || brew install cmake

pip install --user jinja2 pyyaml colorama

# command line utilities aren't available in PATH on macOS with --user
sudo pip install awscli git+https://github.com/bittorrent/simon.git@master#egg=simon
